### ISSUE TITLE
Get all current subscriptions and trials from Google account

### ISSUE THREAD

**Issue by pgb6** [stephenjk41/fastapi-sample#4]
If we want to automatically cancel any subscriptions, or more specifically free trials, by a specified date, we must first obtain all of the current trials on the Google account ,e.g Youtube Premium

**Comment by stephenjk41** [comment]
> If we want to automatically cancel any subscriptions, or more specifically free trials, by a specified date, we must first obtain all of the current trials on the Google account ,e.g Youtube Premium

Does google provide an API service that gets that information
